<?php
require_once 'efsdb/php/core/src/App.php';
require_once 'efsdb/php/core/src/Config.php';

$app = new App(Config::getDataDir(), Config::getSchemaDir());
$phpContent = <<<PHP
<?php
// Auto-generated by EFSDB - Nominated Route for test.tsx
\$componentName = 'test.tsx';
\$basePath = rtrim(\$efsdbSite->basePath(), '/');
\$componentDir = \$efsdbSite->workspacePath('components/' . \$componentName);
\$componentFile = \$efsdbSite->workspacePath('components/' . \$componentName);

if (is_dir(\$componentDir) && file_exists(\$componentDir . '/index.html')) {
    \$html = file_get_contents(\$componentDir . '/index.html');
    \$componentPath = \$basePath . '/components/' . \$componentName;
    \$html = str_replace('href="./_app/', 'href="' . \$componentPath . '/_app/', \$html);
    \$html = str_replace('src="./_app/', 'src="' . \$componentPath . '/_app/', \$html);
    \$html = str_replace('import("./_app/', 'import("' . \$componentPath . '/_app/', \$html);
    \$html = str_replace('href="/_app/', 'href="' . \$componentPath . '/_app/', \$html);
    \$html = str_replace('src="/_app/', 'src="' . \$componentPath . '/_app/', \$html);
    \$html = str_replace('import("/_app/', 'import("' . \$componentPath . '/_app/', \$html);
    echo \$html;
} elseif (file_exists(\$componentFile) && !is_dir(\$componentFile)) {
    \$ext = strtolower(pathinfo(\$componentName, PATHINFO_EXTENSION));
    \$rawUrl = \$basePath . '/components/' . \$componentName;
    echo "<!DOCTYPE html><html><head><title>Preview: {\$componentName}</title>";
    echo "<style>body { font-family: system-ui, sans-serif; padding: 2rem; background: #f9fafb; } .card { background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }</style>";
    echo "</head><body><div class='card'>";
    echo "<h2>{\$componentName}</h2>";
    echo "<p>This is a single-file component. In a full build, this would be compiled by Vite.</p>";
    echo "<div style='margin-top: 1rem; padding: 1rem; background: #f3f4f6; border-radius: 4px; overflow-x: auto;'><pre><code>";
    echo htmlspecialchars(file_get_contents(\$componentFile));
    echo "</code></pre></div>";
    echo "</div></body></html>";
} else {
    echo "<h1>Component {\$componentName} not found</h1>";
}
PHP;

$app->getPublicWorkspace()->writeSiteFile('staging', 'routes/my-new-route2.php', $phpContent, ['mime' => 'application/x-httpd-php']);
echo "Updated my-new-route2.php\n";
