[PHP]
extension_dir = "B:\php\ext"
extension=sodium
extension=mbstring
extension=openssl
error_reporting=E_ALL
display_errors=On
log_errors=On
error_log="B:\Dev\PHPFS\efsdb\php\core\.cache\php-error.log"
date.timezone="America/Toronto"
