[PHP]
extension_dir = "${EFSDB_PHP_EXTENSION_DIR}"
extension = "${EFSDB_PHP_BLAKE3_EXTENSION}"
extension=sodium
extension=mbstring
extension=openssl
error_reporting=E_ALL
display_errors=On
log_errors=On
error_log="${EFSDB_PHP_ERROR_LOG}"
date.timezone="America/Toronto"
