<?php

require_once __DIR__ . '/../../efsdb/php/core/engine/EngineAdapter.php';
require_once __DIR__ . '/../../efsdb/php/core/engine/PurePhpEnvelopeCodec.php';

use EFSDB\Engine\PurePhpEnvelopeCodec;

$codec = new PurePhpEnvelopeCodec();
$fixturesDir = __DIR__;
$files = glob($fixturesDir . '/*.bin');
sort($files);
$expectedPath = $fixturesDir . '/expected_results.json';

if (!function_exists('hash') || !in_array('blake3', hash_algos(), true)) {
    fwrite(STDERR, "Missing blake3 support in PHP runtime. Canonical expected_results.json is generated by generate_fixtures.py.\n");
    exit(1);
}

if (!is_file($expectedPath)) {
    fwrite(STDERR, "Missing canonical expected_results.json. Run python generate_fixtures.py first.\n");
    exit(1);
}

$expectedResults = json_decode((string) file_get_contents($expectedPath), true, 512, JSON_THROW_ON_ERROR);

$results = [];
$mismatches = 0;

foreach ($files as $file) {
    $basename = basename($file);
    $bytes = file_get_contents($file);
    
    $result = $codec->verifyEnvelope($bytes);
    $results[$basename] = $result;
    if (($expectedResults[$basename] ?? null) !== $result) {
        echo "FAIL {$basename}\n";
        echo "Expected: " . json_encode($expectedResults[$basename] ?? null, JSON_UNESCAPED_SLASHES) . "\n";
        echo "Actual:   " . json_encode($result, JSON_UNESCAPED_SLASHES) . "\n";
        $mismatches++;
    } else {
        echo "PASS {$basename}\n";
    }
}

if ($mismatches > 0) {
    fwrite(STDERR, "PHP parity mismatch against canonical expected_results.json\n");
    exit(1);
}

echo "PHP parity matches canonical expected_results.json\n";
